
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Newtonsoft.Json;

namespace FitnessCenterService.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Client
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {

            this.Workouts = new HashSet<Workout>();

        }


        public int ClientId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public Nullable<System.DateTime> BirthDate { get; set; }

        public string Email { get; set; }

        public Nullable<System.DateTime> MemberSince { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Workout> Workouts { get; set; }

    }

}
