
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Newtonsoft.Json;

namespace FitnessCenterService.Models
{

    using System;
    using System.Collections.Generic;

    public partial class ExerciseType
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExerciseType()
        {

            this.Exercises = new HashSet<Exercis>();

        }


        public int ExerciseTypeId { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public Nullable<int> Duration { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Exercis> Exercises { get; set; }

    }

}
