
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Newtonsoft.Json;

namespace FitnessCenterService.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Exercis
    {

        public int ExerciseId { get; set; }

        public int ExerciseTypeId { get; set; }

        public int WorkoutId { get; set; }

        public Nullable<int> Count { get; set; }



        public virtual ExerciseType ExerciseType { get; set; }
        [JsonIgnore]
        public virtual Workout Workout { get; set; }

    }

}
