
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FitnessCenterService.Models
{

using System;
    using System.Collections.Generic;
    
public partial class SSO
{

    public int SSOId { get; set; }

    public int SSOValue { get; set; }

    public int UserId { get; set; }

    public System.DateTime ExpirationDate { get; set; }



    public virtual User User { get; set; }

}

}
