
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Newtonsoft.Json;

namespace FitnessCenterService.Models
{

    using System;
    using System.Collections.Generic;

    public partial class User
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {

            this.SSOes = new HashSet<SSO>();

            this.Workouts = new HashSet<Workout>();

        }


        public int UserId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Email { get; set; }

        public Nullable<bool> IsEnabled { get; set; }
        [JsonIgnore]
        public Nullable<int> PasswordHash { get; set; }
        [JsonIgnore]
        public Nullable<bool> IsAdmin { get; set; }
        [JsonIgnore]
        public Nullable<bool> IsChiefTrainer { get; set; }



        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<SSO> SSOes { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Workout> Workouts { get; set; }

    }

}
