
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using Newtonsoft.Json;

namespace FitnessCenterService.Models
{

    using System;
    using System.Collections.Generic;

    public partial class Workout
    {

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Workout()
        {

            this.Exercises = new HashSet<Exercis>();

        }


        public int WorkoutId { get; set; }

        public System.DateTime Date { get; set; }

        public int ClientId { get; set; }

        public int UserId { get; set; }

        public bool IsCompleted { get; set; }



        public virtual Client Client { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<Exercis> Exercises { get; set; }
        [JsonIgnore]
        public virtual User User { get; set; }

    }

}
